### ISSUE TITLE
Some sky music on the internet is in txt format. Is it possible to read the txt file from sky auto music app?

### ISSUE THREAD

**Issue by hardiwb** [Viwyn/Sky-Music-Player#1]
Some sky music on the internet is in txt format. Is it possible to read the txt file from sky auto music app?
[Example song.txt](https://github.com/Viwyn/Sky-Music-Player/files/15135915/Example.song.txt)

**Comment by Viwyn** [comment]
it is possible to read a txt file, but unfortunately, the example file is written in an old format which the player cannot read
I'll try to find a way to convert it but I have no idea how this file format is written.

**Comment by Viwyn** [comment]
Yea sorry, after reading through it, still can't figure out much. Will try to implement if I can get like an explanation to the numbers but for now, its not planned.
