### ISSUE TITLE
some notes not playing?

### ISSUE THREAD

**Issue by Rhysand4rch** [Viwyn/Sky-Music-Player#5]
it, seemingly randomly, skips some notes, and which notes change depending on which instrument you're using? ends up sounding rather strange. i assume it might be that there are different parts and it makes the whole thing with different instruments, but im unsure if thats the case.

**Comment by Rhysand4rch** [comment]
i figured it out! you have to be in an area with the correct pitch

**Comment by Rhysand4rch** [comment]
i figured it out! you have to be in an area with the correct pitch

**Comment by Rhysand4rch** [comment]
hm nevermind  it definitely played more of it but not all

**Comment by Viwyn** [comment]
It only has 15 notes that it can play, anything out of that range gets skipped. If you got the MIDI file from an external source, some notes are outside of that range so some transposing is needed. Do you have a MIDI file that I can use to test?

**Comment by Rhysand4rch** [comment]
im only using skysheet files from sky music, so they all should work.

**Comment by Viwyn** [comment]
Theoretically they should all work but there might be some edge cases that I might have missed, can you tell me the name or the song or provide the file in some way so I can try and reproduce it?

**Comment by Rhysand4rch** [comment]
the exact song i play doesnt matter, all of them skip notes. ive done testing and trying to fix it and the notes that it skips are different each time, even if im in the same place (this leads me to believe that when i tested in an area with the correct key it was simply a fluke that it played more). though there does seem to be some consistency with certain notes almost always being skipped. its particularly bad on songs that go pretty fast but also happens with slower sections too.  i'm going to screen record a few attempts with the same song ive mostly been using to test (on sky music its called HTTYD (Blue) and is 220 BPM and the pitch is C).

**Comment by Rhysand4rch** [comment]
ive only downloaded 4 songs btw, all have the same issue. they are:

- Undertale - Undertale
- Hollow Knight - Main Theme
- HTTYD (Blue)
- Undertale - Hopes and Dreams (Mug)

**Comment by Viwyn** [comment]
I've tried both undertale songs and the HTTYD (Blue). They seem to [work just fine](https://youtu.be/dq8Oiq9UQzo) for me. Maybe its the system your running the script on? What are your specs?

**Comment by Rhysand4rch** [comment]
it might be lag, im on a microsoft surface and its not incredible but its also not bad, it runs Sky perfectly fine.
heres some specs:
processor: 12th Gen Intel Core i5-1235U   2.50 GHz
graphics: Intel Iris Xe Graphics
RAM: 8.00 GB (7.83 GB usable)

i tried screen recording but sky did not agree with it so i [recorded on my phone instead](https://youtu.be/Azrmnup3upk) i did record multiple but am having issues uploading so youll just have to take my word on the fact that it keeps changing which notes are or arent played.

**Comment by Rhysand4rch** [comment]
goddamnit the video has no audio for some reason, hope you can still tell that its not playing everything

**Comment by Viwyn** [comment]
Yea unfortunately, I can't replicated this so I'll be closing this. So sorry.
